# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pengwang/cloud_platform/project/github/libjsonrpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pengwang/cloud_platform/project/github/libjsonrpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pengwang/cloud_platform/project/github/libjsonrpc/CMakeFiles /home/pengwang/cloud_platform/project/github/libjsonrpc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pengwang/cloud_platform/project/github/libjsonrpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jsonrpc

# Build rule for target.
jsonrpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsonrpc
.PHONY : jsonrpc

# fast build rule for target.
jsonrpc/fast:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/build
.PHONY : jsonrpc/fast

examples/example.o: examples/example.cpp.o

.PHONY : examples/example.o

# target to build an object file
examples/example.cpp.o:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/examples/example.cpp.o
.PHONY : examples/example.cpp.o

examples/example.i: examples/example.cpp.i

.PHONY : examples/example.i

# target to preprocess a source file
examples/example.cpp.i:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/examples/example.cpp.i
.PHONY : examples/example.cpp.i

examples/example.s: examples/example.cpp.s

.PHONY : examples/example.s

# target to generate assembly for a file
examples/example.cpp.s:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/examples/example.cpp.s
.PHONY : examples/example.cpp.s

src/jsonrpc/server/connection.o: src/jsonrpc/server/connection.cpp.o

.PHONY : src/jsonrpc/server/connection.o

# target to build an object file
src/jsonrpc/server/connection.cpp.o:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/connection.cpp.o
.PHONY : src/jsonrpc/server/connection.cpp.o

src/jsonrpc/server/connection.i: src/jsonrpc/server/connection.cpp.i

.PHONY : src/jsonrpc/server/connection.i

# target to preprocess a source file
src/jsonrpc/server/connection.cpp.i:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/connection.cpp.i
.PHONY : src/jsonrpc/server/connection.cpp.i

src/jsonrpc/server/connection.s: src/jsonrpc/server/connection.cpp.s

.PHONY : src/jsonrpc/server/connection.s

# target to generate assembly for a file
src/jsonrpc/server/connection.cpp.s:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/connection.cpp.s
.PHONY : src/jsonrpc/server/connection.cpp.s

src/jsonrpc/server/connection_manager.o: src/jsonrpc/server/connection_manager.cpp.o

.PHONY : src/jsonrpc/server/connection_manager.o

# target to build an object file
src/jsonrpc/server/connection_manager.cpp.o:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/connection_manager.cpp.o
.PHONY : src/jsonrpc/server/connection_manager.cpp.o

src/jsonrpc/server/connection_manager.i: src/jsonrpc/server/connection_manager.cpp.i

.PHONY : src/jsonrpc/server/connection_manager.i

# target to preprocess a source file
src/jsonrpc/server/connection_manager.cpp.i:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/connection_manager.cpp.i
.PHONY : src/jsonrpc/server/connection_manager.cpp.i

src/jsonrpc/server/connection_manager.s: src/jsonrpc/server/connection_manager.cpp.s

.PHONY : src/jsonrpc/server/connection_manager.s

# target to generate assembly for a file
src/jsonrpc/server/connection_manager.cpp.s:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/connection_manager.cpp.s
.PHONY : src/jsonrpc/server/connection_manager.cpp.s

src/jsonrpc/server/io_service_pool.o: src/jsonrpc/server/io_service_pool.cpp.o

.PHONY : src/jsonrpc/server/io_service_pool.o

# target to build an object file
src/jsonrpc/server/io_service_pool.cpp.o:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/io_service_pool.cpp.o
.PHONY : src/jsonrpc/server/io_service_pool.cpp.o

src/jsonrpc/server/io_service_pool.i: src/jsonrpc/server/io_service_pool.cpp.i

.PHONY : src/jsonrpc/server/io_service_pool.i

# target to preprocess a source file
src/jsonrpc/server/io_service_pool.cpp.i:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/io_service_pool.cpp.i
.PHONY : src/jsonrpc/server/io_service_pool.cpp.i

src/jsonrpc/server/io_service_pool.s: src/jsonrpc/server/io_service_pool.cpp.s

.PHONY : src/jsonrpc/server/io_service_pool.s

# target to generate assembly for a file
src/jsonrpc/server/io_service_pool.cpp.s:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/io_service_pool.cpp.s
.PHONY : src/jsonrpc/server/io_service_pool.cpp.s

src/jsonrpc/server/transport_server.o: src/jsonrpc/server/transport_server.cpp.o

.PHONY : src/jsonrpc/server/transport_server.o

# target to build an object file
src/jsonrpc/server/transport_server.cpp.o:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/transport_server.cpp.o
.PHONY : src/jsonrpc/server/transport_server.cpp.o

src/jsonrpc/server/transport_server.i: src/jsonrpc/server/transport_server.cpp.i

.PHONY : src/jsonrpc/server/transport_server.i

# target to preprocess a source file
src/jsonrpc/server/transport_server.cpp.i:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/transport_server.cpp.i
.PHONY : src/jsonrpc/server/transport_server.cpp.i

src/jsonrpc/server/transport_server.s: src/jsonrpc/server/transport_server.cpp.s

.PHONY : src/jsonrpc/server/transport_server.s

# target to generate assembly for a file
src/jsonrpc/server/transport_server.cpp.s:
	$(MAKE) -f CMakeFiles/jsonrpc.dir/build.make CMakeFiles/jsonrpc.dir/src/jsonrpc/server/transport_server.cpp.s
.PHONY : src/jsonrpc/server/transport_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... jsonrpc"
	@echo "... examples/example.o"
	@echo "... examples/example.i"
	@echo "... examples/example.s"
	@echo "... src/jsonrpc/server/connection.o"
	@echo "... src/jsonrpc/server/connection.i"
	@echo "... src/jsonrpc/server/connection.s"
	@echo "... src/jsonrpc/server/connection_manager.o"
	@echo "... src/jsonrpc/server/connection_manager.i"
	@echo "... src/jsonrpc/server/connection_manager.s"
	@echo "... src/jsonrpc/server/io_service_pool.o"
	@echo "... src/jsonrpc/server/io_service_pool.i"
	@echo "... src/jsonrpc/server/io_service_pool.s"
	@echo "... src/jsonrpc/server/transport_server.o"
	@echo "... src/jsonrpc/server/transport_server.i"
	@echo "... src/jsonrpc/server/transport_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

